# Generated by Django 6.0.6 on 2026-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('wifi', 'WiFi'), ('mess', 'Mess Food'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
